// Generated by Melange

import * as React from "react";

import './globals.css'
;

import { Inter } from 'next/font/google'
;

const inter = Inter({ subsets: ['latin'] })
;

function IndexLayout(Props) {
  var children = Props.children;
  return React.createElement("html", {
              lang: "en"
            }, React.createElement("body", {
                  className: inter.className
                }, children));
}

var metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

var make = IndexLayout;

export {
  metadata ,
  make ,
}
/*  Not a pure module */
