// Generated by Melange

import * as React from "react";
import * as Components__Link from "./Link.js";
import * as Components__Image from "./Image.js";

function IndexPage(Props) {
  return React.createElement("main", {
              className: "flex min-h-screen flex-col items-center justify-between p-24"
            }, React.createElement("div", {
                  className: "z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex"
                }, React.createElement("p", {
                      className: "fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30"
                    }, "Get started by editing", React.createElement("code", {
                          className: "font-mono font-bold ml-2"
                        }, "src/app/page.tsx")), React.createElement("div", {
                      className: "fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none"
                    }, React.createElement("a", {
                          className: "pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0",
                          href: "https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                          rel: "noopener noreferrer",
                          target: "_blank"
                        }, "By", React.createElement(Components__Image.make, {
                              className: "dark:invert",
                              src: "/vercel.svg",
                              alt: "Vercel Logo",
                              width: 100,
                              height: 24,
                              priority: true
                            })))), React.createElement("div", {
                  className: "relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]"
                }, React.createElement(Components__Image.make, {
                      className: "relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert",
                      src: "/next.svg",
                      alt: "Next.js Logo",
                      width: 180,
                      height: 37,
                      priority: true
                    })), React.createElement("div", {
                  className: "mb-32 grid text-center lg:mb-0 lg:grid-cols-4 lg:text-left"
                }, React.createElement("a", {
                      className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                      href: "https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, React.createElement("h2", {
                          className: "mb-3 text-2xl font-semibold"
                        }, "Docs", React.createElement("span", {
                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                            }, "\u2192")), React.createElement("p", {
                          className: "m-0 max-w-[30ch] text-sm opacity-50"
                        }, "Find in-depth information about Next.js features and API.")), React.createElement("a", {
                      className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                      href: "https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, React.createElement("h2", {
                          className: "mb-3 text-2xl font-semibold"
                        }, "Learn", React.createElement("span", {
                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                            }, "\u2192")), React.createElement("p", {
                          className: "m-0 max-w-[30ch] text-sm opacity-50"
                        }, "Learn about Next.js in an interactive course with quizzes!")), React.createElement("a", {
                      className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                      href: "https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, React.createElement("h2", {
                          className: "mb-3 text-2xl font-semibold"
                        }, "Templates", React.createElement("span", {
                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                            }, "\u2192")), React.createElement("p", {
                          className: "m-0 max-w-[30ch] text-sm opacity-50"
                        }, "Explore the Next.js 13 playground.")), React.createElement("a", {
                      className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                      href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, React.createElement("h2", {
                          className: "mb-3 text-2xl font-semibold"
                        }, "Deploy", React.createElement("span", {
                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                            }, "\u2192")), React.createElement("p", {
                          className: "m-0 max-w-[30ch] text-sm opacity-50"
                        }, "Instantly deploy your Next.js site to a shareable URL with Vercel.")), React.createElement(Components__Link.make, {
                      className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                      href: "/dogs",
                      children: null
                    }, React.createElement("h2", {
                          className: "flex mb-3 text-2xl font-semibold"
                        }, React.createElement("img", {
                              className: "mr-1",
                              alt: "Reason Logo",
                              src: "/icon_50.png",
                              width: "30"
                            }), "Dogs", React.createElement("span", {
                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                            }, "\u2192")), React.createElement("p", {
                          className: "m-0 max-w-[30ch] text-sm opacity-50"
                        }, "View a dog picture")), React.createElement(Components__Link.make, {
                      className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                      href: "/jokes",
                      children: null
                    }, React.createElement("h2", {
                          className: "flex mb-3 text-2xl font-semibold"
                        }, React.createElement("img", {
                              className: "mr-1",
                              alt: "Reason Logo",
                              src: "/icon_50.png",
                              width: "30"
                            }), "Jokes", React.createElement("span", {
                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                            }, "\u2192")), React.createElement("p", {
                          className: "m-0 max-w-[30ch] text-sm opacity-50"
                        }, "Read a joke"))));
}

var make = IndexPage;

export {
  make ,
}
/* react Not a pure module */
